In [1]:
import pandas as pd

lpi_df = pd.read_csv("../International_LPI_2018.csv")
lpi_df

Country   LPI  Customs  Infrastructure  International shipments  \
0         Germany  4.20     4.09            4.37                     3.86   
1          Sweden  4.05     4.05            4.24                     3.92   
2         Belgium  4.04     3.66            3.98                     3.99   
3         Austria  4.03     3.71            4.18                     3.88   
4           Japan  4.03     3.99            4.25                     3.59   
..            ...   ...      ...             ...                      ...   
155  Sierra Leone  2.08     1.82            1.82                     2.18   
156         Niger  2.07     1.77            2.00                     2.00   
157       Burundi  2.06     1.69            1.95                     2.21   
158        Angola  2.05     1.57            1.86                     2.20   
159   Afghanistan  1.95     1.73            1.81                     2.10   

     Logistics quality and competence  Tracking and tracing  Timeliness  
0                                4.31                  4.24        4.39  
1                                3.98                  3.88        4.28  
2                                4.13                  4.05        4.41  
3                                4.08                  4.09        4.25  
4                                4.09                  4.05        4.25  
..                                ...                   ...         ...  
155                              2.00                  2.27        2.34  
156                              2.10                  2.22        2.33  
157                              2.33                  2.01        2.17  
158                              2.00                  2.00        2.59  
159                              1.92                  1.70        2.38  

[160 rows x 8 columns]

In [3]:
lpi_components = [
    'Customs',
    'Infrastructure',
    'International shipments',
    'Logistics quality and competence',
    'Tracking and tracing',
    'Timeliness'
]

lpi_components = lpi_df[lpi_components]
lpi_components

Customs  Infrastructure  International shipments  \
0       4.09            4.37                     3.86   
1       4.05            4.24                     3.92   
2       3.66            3.98                     3.99   
3       3.71            4.18                     3.88   
4       3.99            4.25                     3.59   
..       ...             ...                      ...   
155     1.82            1.82                     2.18   
156     1.77            2.00                     2.00   
157     1.69            1.95                     2.21   
158     1.57            1.86                     2.20   
159     1.73            1.81                     2.10   

     Logistics quality and competence  Tracking and tracing  Timeliness  
0                                4.31                  4.24        4.39  
1                                3.98                  3.88        4.28  
2                                4.13                  4.05        4.41  
3                                4.08                  4.09        4.25  
4                                4.09                  4.05        4.25  
..                                ...                   ...         ...  
155                              2.00                  2.27        2.34  
156                              2.10                  2.22        2.33  
157                              2.33                  2.01        2.17  
158                              2.00                  2.00        2.59  
159                              1.92                  1.70        2.38  

[160 rows x 6 columns]

In [6]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
lpi_components_standard_scaled = standard_scaler.fit_transform(lpi_components)
lpi_components_standard_scaled

array([[ 2.45929193e+00,  2.45079888e+00,  2.00521459e+00,
         2.45383489e+00,  2.19076231e+00,  2.01081279e+00],
       [ 2.38986025e+00,  2.25737594e+00,  2.12201612e+00,
         1.91186851e+00,  1.60167726e+00,  1.81905778e+00],
       [ 1.71290133e+00,  1.87053005e+00,  2.25828457e+00,
         2.15821686e+00,  1.87985631e+00,  2.04567734e+00],
       [ 1.79969094e+00,  2.16810381e+00,  2.04414844e+00,
         2.07610075e+00,  1.94531021e+00,  1.76676095e+00],
       [ 2.28571272e+00,  2.27225463e+00,  1.47960771e+00,
         2.09252397e+00,  1.87985631e+00,  1.76676095e+00],
       [ 2.16420728e+00,  2.21273988e+00,  1.65481000e+00,
         2.09252397e+00,  1.83076589e+00,  1.76676095e+00],
       [ 2.11213351e+00,  1.98955956e+00,  1.46014079e+00,
         2.10894719e+00,  1.92894673e+00,  1.88878687e+00],
       [ 2.16420728e+00,  1.84077268e+00,  1.36280618e+00,
         1.96113818e+00,  2.09258147e+00,  2.04567734e+00],
       [ 1.90383846e+00,  1.94492349e+00,  1.635

In [7]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)

In [8]:
pca.fit(lpi_components_standard_scaled)

PCA(n_components=1)

In [10]:
pca.explained_variance_ratio_[0]

0.9225762894921422

In [11]:
tranformed = pca.transform(lpi_components_standard_scaled)
tranformed[:10]

array([[5.54547364],
       [4.93808946],
       [4.86533482],
       [4.81834623],
       [4.81569261],
       [4.79085083],
       [4.69701109],
       [4.68746366],
       [4.65614658],
       [4.58455542]])

In [19]:
pca.components_

array([[0.40728498, 0.41303479, 0.39604297, 0.41660675, 0.41067906,
        0.40552768]])

In [13]:
print(tranformed.min(), tranformed.max())

-3.816178904589359 5.545473639886474


In [20]:
 import numpy as np 
np.average(lpi_components, axis=1, weights=pca.components_[0])[:10]

array([4.2122752 , 4.05869046, 4.03685368, 4.03281921, 4.03928615,
       4.03042283, 4.00731942, 4.00371973, 3.99503935, 3.98022523])